// Copyright (c) 2014-2015 The OpenSSL Project.  All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer. 
// 
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in
//    the documentation and/or other materials provided with the
//    distribution.
// 
// 3. All advertising materials mentioning features or use of this
//    software must display the following acknowledgment:
//    "This product includes software developed by the OpenSSL Project
//    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
// 
// 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
//    endorse or promote products derived from this software without
//    prior written permission. For written permission, please contact
//    openssl-core@openssl.org.
// 
// 5. Products derived from this software may not be called "OpenSSL"
//    nor may "OpenSSL" appear in their names without prior written
//    permission of the OpenSSL Project.
// 
// 6. Redistributions of any form whatsoever must retain the following
//    acknowledgment:
//    "This product includes software developed by the OpenSSL Project
//    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
// 
// THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
// EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
// ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef HEADER_EWES_ERR_H
#define HEADER_EWES_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_EWES_strings(void);
static void ERR_unload_EWES_strings(void);
static void ERR_EWES_error(int function, int reason, char *file, int line);
# define EWESerr(f,r) ERR_EWES_error((f),(r),__FILE__,__LINE__)

/* Error codes for the EWES functions. */

/* Function codes. */
# define EWES_F_EWES_CTRL                                 103
# define EWES_F_EWES_FINISH                               104
# define EWES_F_EWES_INIT                                 100
# define EWES_F_EWES_RAND_BYTES                           101
# define EWES_F_EWES_RAND_PSEUDOBYTES                     102

/* Reason codes. */
# define EWES_R_ALREADY_LOADED                            103
# define EWES_R_CTRL_COMMAND_NOT_IMPLEMENTED              104
# define EWES_R_DSO_FAILURE                               105
# define EWES_R_LOCKING_ERROR                             107
# define EWES_R_NOT_INITIALISED                           100
# define EWES_R_NOT_LOADED                                106
# define EWES_R_REQUEST_FAILED                            101
# define EWES_R_RETURNED_LESS_BYTES                       102

#ifdef  __cplusplus
}
#endif
#endif
