// Copyright (c) 2014-2015 The OpenSSL Project.  All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer. 
// 
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in
//    the documentation and/or other materials provided with the
//    distribution.
// 
// 3. All advertising materials mentioning features or use of this
//    software must display the following acknowledgment:
//    "This product includes software developed by the OpenSSL Project
//    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
// 
// 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
//    endorse or promote products derived from this software without
//    prior written permission. For written permission, please contact
//    openssl-core@openssl.org.
// 
// 5. Products derived from this software may not be called "OpenSSL"
//    nor may "OpenSSL" appear in their names without prior written
//    permission of the OpenSSL Project.
// 
// 6. Redistributions of any form whatsoever must retain the following
//    acknowledgment:
//    "This product includes software developed by the OpenSSL Project
//    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
// 
// THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
// EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
// ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "ewes_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA EWES_str_functs[] = {
    {ERR_FUNC(EWES_F_EWES_CTRL), "EWES_CTRL"},
    {ERR_FUNC(EWES_F_EWES_FINISH), "EWES_FINISH"},
    {ERR_FUNC(EWES_F_EWES_INIT), "EWES_INIT"},
    {ERR_FUNC(EWES_F_EWES_RAND_BYTES), "EWES_RAND_BYTES"},
    {ERR_FUNC(EWES_F_EWES_RAND_PSEUDOBYTES), "EWES_RAND_PSEUDOBYTES"},
    {0, NULL}
};

static ERR_STRING_DATA EWES_str_reasons[] = {
    {ERR_REASON(EWES_R_ALREADY_LOADED), "already loaded"},
    {ERR_REASON(EWES_R_CTRL_COMMAND_NOT_IMPLEMENTED),
     "ctrl command not implemented"},
    {ERR_REASON(EWES_R_DSO_FAILURE), "dso failure"},
    {ERR_REASON(EWES_R_LOCKING_ERROR), "locking error"},
    {ERR_REASON(EWES_R_NOT_INITIALISED), "not initialised"},
    {ERR_REASON(EWES_R_NOT_LOADED), "not loaded"},
    {ERR_REASON(EWES_R_REQUEST_FAILED), "request failed"},
    {ERR_REASON(EWES_R_RETURNED_LESS_BYTES), "returned less bytes"},
    {0, NULL}
};

#endif

#ifdef EWES_LIB_NAME
static ERR_STRING_DATA EWES_lib_name[] = {
    {0, EWES_LIB_NAME},
    {0, NULL}
};
#endif

static int EWES_lib_error_code = 0;
static int EWES_error_init = 1;

static void ERR_load_EWES_strings(void)
{
    if (EWES_lib_error_code == 0)
        EWES_lib_error_code = ERR_get_next_error_library();

    if (EWES_error_init) {
        EWES_error_init = 0;
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(EWES_lib_error_code, EWES_str_functs);
        ERR_load_strings(EWES_lib_error_code, EWES_str_reasons);
#endif

#ifdef EWES_LIB_NAME
        EWES_lib_name->error = ERR_PACK(EWES_lib_error_code, 0, 0);
        ERR_load_strings(0, EWES_lib_name);
#endif
    }
}

static void ERR_unload_EWES_strings(void)
{
    if (EWES_error_init == 0) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(EWES_lib_error_code, EWES_str_functs);
        ERR_unload_strings(EWES_lib_error_code, EWES_str_reasons);
#endif

#ifdef EWES_LIB_NAME
        ERR_unload_strings(0, EWES_lib_name);
#endif
        EWES_error_init = 1;
    }
}

static void ERR_EWES_error(int function, int reason, char *file, int line)
{
    if (EWES_lib_error_code == 0)
        EWES_lib_error_code = ERR_get_next_error_library();
    ERR_PUT_error(EWES_lib_error_code, function, reason, file, line);
}
